# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master
#  - develop
  - staging

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Staging
    condition: eq(variables['build.sourceBranch'], 'refs/heads/staging')
    jobs:
      - job: Ship
        displayName: Ship the ReactJS to AWS S3
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              REACT_APP_API_URL=https://sim-core-api.staging.devops.idc.vegaturbo.com.br/api/v1 npm run build
            displayName: 'npm install and build'

          - script: |
              python -m pip install --upgrade pip==9.0.3 setuptools wheel
              pip install awscli --user
            displayName: 'Install AWS tools'

          - task: S3Upload@1
            inputs:
              awsCredentials: 'AWSVegaIT'
              regionName: 'us-east-2'
              bucketName: 'sim-staging.devops.idc.vegaturbo.com.br'
              sourceFolder: '$(System.DefaultWorkingDirectory)/build'
              globExpressions: '**'

          - task: AWSShellScript@1
            inputs:
              awsCredentials: 'AWSVegaIT'
              regionName: 'us-east-2'
              scriptType: 'inline'
              inlineScript: 'aws cloudfront create-invalidation --distribution-id E31CPCPLINL03O --paths "/*"'

  - stage: Production
    condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
    jobs:
      - job: Ship
        displayName: Ship the ReactJS to AWS S3
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              REACT_APP_API_URL=https://sim-core-api.devops.idc.vegaturbo.com.br/api/v1 npm run build
            displayName: 'npm install and build'

          - script: |
              python -m pip install --upgrade pip==9.0.3 setuptools wheel
              pip install awscli --user
            displayName: 'Install AWS tools'

          - task: S3Upload@1
            inputs:
              awsCredentials: 'AWSVegaIT'
              regionName: 'us-east-2'
              bucketName: 'sim.devops.idc.vegaturbo.com.br'
              sourceFolder: '$(System.DefaultWorkingDirectory)/build'
              globExpressions: '**'

          - task: AWSShellScript@1
            inputs:
              awsCredentials: 'AWSVegaIT'
              regionName: 'us-east-2'
              scriptType: 'inline'
              inlineScript: 'aws cloudfront create-invalidation --distribution-id E1VMQ19Y2M2Z1Z --paths "/*"'

